name: word2vec
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip

  # Base conda deps
  - setuptools
  - setuptools-scm
  - pylint
  - flake8
  - black
  - isort
  - twine
  - wheel
  - pytest
  - pytest-cov

  # This project conda deps
  - numpy
  - scikit-learn
  - notebook
  - jupyterlab
  - nltk

  - pip:
    # This project pip deps
